// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/java/com/orbekk/protobuf/Data.proto

package com.orbekk.protobuf;

public final class Data {
  private Data() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface RequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.orbekk.protobuf.Request)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string full_service_name = 1;</code>
     */
    boolean hasFullServiceName();
    /**
     * <code>optional string full_service_name = 1;</code>
     */
    java.lang.String getFullServiceName();
    /**
     * <code>optional string full_service_name = 1;</code>
     */
    com.google.protobuf.ByteString
        getFullServiceNameBytes();

    /**
     * <code>optional string method_name = 2;</code>
     */
    boolean hasMethodName();
    /**
     * <code>optional string method_name = 2;</code>
     */
    java.lang.String getMethodName();
    /**
     * <code>optional string method_name = 2;</code>
     */
    com.google.protobuf.ByteString
        getMethodNameBytes();

    /**
     * <code>optional bytes request_proto = 3;</code>
     */
    boolean hasRequestProto();
    /**
     * <code>optional bytes request_proto = 3;</code>
     */
    com.google.protobuf.ByteString getRequestProto();

    /**
     * <code>optional int64 request_id = 4;</code>
     */
    boolean hasRequestId();
    /**
     * <code>optional int64 request_id = 4;</code>
     */
    long getRequestId();
  }
  /**
   * <pre>
   * Next tag: 6
   * </pre>
   *
   * Protobuf type {@code com.orbekk.protobuf.Request}
   */
  public  static final class Request extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.orbekk.protobuf.Request)
      RequestOrBuilder {
    // Use Request.newBuilder() to construct.
    private Request(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Request() {
      fullServiceName_ = "";
      methodName_ = "";
      requestProto_ = com.google.protobuf.ByteString.EMPTY;
      requestId_ = 0L;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Request(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              fullServiceName_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              methodName_ = bs;
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              requestProto_ = input.readBytes();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              requestId_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.orbekk.protobuf.Data.internal_static_com_orbekk_protobuf_Request_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.orbekk.protobuf.Data.internal_static_com_orbekk_protobuf_Request_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.orbekk.protobuf.Data.Request.class, com.orbekk.protobuf.Data.Request.Builder.class);
    }

    private int bitField0_;
    public static final int FULL_SERVICE_NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object fullServiceName_;
    /**
     * <code>optional string full_service_name = 1;</code>
     */
    public boolean hasFullServiceName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string full_service_name = 1;</code>
     */
    public java.lang.String getFullServiceName() {
      java.lang.Object ref = fullServiceName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          fullServiceName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string full_service_name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getFullServiceNameBytes() {
      java.lang.Object ref = fullServiceName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        fullServiceName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int METHOD_NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object methodName_;
    /**
     * <code>optional string method_name = 2;</code>
     */
    public boolean hasMethodName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string method_name = 2;</code>
     */
    public java.lang.String getMethodName() {
      java.lang.Object ref = methodName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          methodName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string method_name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getMethodNameBytes() {
      java.lang.Object ref = methodName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        methodName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int REQUEST_PROTO_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString requestProto_;
    /**
     * <code>optional bytes request_proto = 3;</code>
     */
    public boolean hasRequestProto() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional bytes request_proto = 3;</code>
     */
    public com.google.protobuf.ByteString getRequestProto() {
      return requestProto_;
    }

    public static final int REQUEST_ID_FIELD_NUMBER = 4;
    private long requestId_;
    /**
     * <code>optional int64 request_id = 4;</code>
     */
    public boolean hasRequestId() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional int64 request_id = 4;</code>
     */
    public long getRequestId() {
      return requestId_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, fullServiceName_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, methodName_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, requestProto_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt64(4, requestId_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, fullServiceName_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, methodName_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, requestProto_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, requestId_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.orbekk.protobuf.Data.Request)) {
        return super.equals(obj);
      }
      com.orbekk.protobuf.Data.Request other = (com.orbekk.protobuf.Data.Request) obj;

      boolean result = true;
      result = result && (hasFullServiceName() == other.hasFullServiceName());
      if (hasFullServiceName()) {
        result = result && getFullServiceName()
            .equals(other.getFullServiceName());
      }
      result = result && (hasMethodName() == other.hasMethodName());
      if (hasMethodName()) {
        result = result && getMethodName()
            .equals(other.getMethodName());
      }
      result = result && (hasRequestProto() == other.hasRequestProto());
      if (hasRequestProto()) {
        result = result && getRequestProto()
            .equals(other.getRequestProto());
      }
      result = result && (hasRequestId() == other.hasRequestId());
      if (hasRequestId()) {
        result = result && (getRequestId()
            == other.getRequestId());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasFullServiceName()) {
        hash = (37 * hash) + FULL_SERVICE_NAME_FIELD_NUMBER;
        hash = (53 * hash) + getFullServiceName().hashCode();
      }
      if (hasMethodName()) {
        hash = (37 * hash) + METHOD_NAME_FIELD_NUMBER;
        hash = (53 * hash) + getMethodName().hashCode();
      }
      if (hasRequestProto()) {
        hash = (37 * hash) + REQUEST_PROTO_FIELD_NUMBER;
        hash = (53 * hash) + getRequestProto().hashCode();
      }
      if (hasRequestId()) {
        hash = (37 * hash) + REQUEST_ID_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getRequestId());
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.orbekk.protobuf.Data.Request parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.orbekk.protobuf.Data.Request parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.orbekk.protobuf.Data.Request parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.orbekk.protobuf.Data.Request parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.orbekk.protobuf.Data.Request parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.orbekk.protobuf.Data.Request parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.orbekk.protobuf.Data.Request parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.orbekk.protobuf.Data.Request parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.orbekk.protobuf.Data.Request parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.orbekk.protobuf.Data.Request parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.orbekk.protobuf.Data.Request prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Next tag: 6
     * </pre>
     *
     * Protobuf type {@code com.orbekk.protobuf.Request}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.orbekk.protobuf.Request)
        com.orbekk.protobuf.Data.RequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.orbekk.protobuf.Data.internal_static_com_orbekk_protobuf_Request_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.orbekk.protobuf.Data.internal_static_com_orbekk_protobuf_Request_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.orbekk.protobuf.Data.Request.class, com.orbekk.protobuf.Data.Request.Builder.class);
      }

      // Construct using com.orbekk.protobuf.Data.Request.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        fullServiceName_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        methodName_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        requestProto_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        requestId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.orbekk.protobuf.Data.internal_static_com_orbekk_protobuf_Request_descriptor;
      }

      public com.orbekk.protobuf.Data.Request getDefaultInstanceForType() {
        return com.orbekk.protobuf.Data.Request.getDefaultInstance();
      }

      public com.orbekk.protobuf.Data.Request build() {
        com.orbekk.protobuf.Data.Request result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.orbekk.protobuf.Data.Request buildPartial() {
        com.orbekk.protobuf.Data.Request result = new com.orbekk.protobuf.Data.Request(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.fullServiceName_ = fullServiceName_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.methodName_ = methodName_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.requestProto_ = requestProto_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.requestId_ = requestId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.orbekk.protobuf.Data.Request) {
          return mergeFrom((com.orbekk.protobuf.Data.Request)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.orbekk.protobuf.Data.Request other) {
        if (other == com.orbekk.protobuf.Data.Request.getDefaultInstance()) return this;
        if (other.hasFullServiceName()) {
          bitField0_ |= 0x00000001;
          fullServiceName_ = other.fullServiceName_;
          onChanged();
        }
        if (other.hasMethodName()) {
          bitField0_ |= 0x00000002;
          methodName_ = other.methodName_;
          onChanged();
        }
        if (other.hasRequestProto()) {
          setRequestProto(other.getRequestProto());
        }
        if (other.hasRequestId()) {
          setRequestId(other.getRequestId());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.orbekk.protobuf.Data.Request parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.orbekk.protobuf.Data.Request) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object fullServiceName_ = "";
      /**
       * <code>optional string full_service_name = 1;</code>
       */
      public boolean hasFullServiceName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string full_service_name = 1;</code>
       */
      public java.lang.String getFullServiceName() {
        java.lang.Object ref = fullServiceName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            fullServiceName_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string full_service_name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getFullServiceNameBytes() {
        java.lang.Object ref = fullServiceName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          fullServiceName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string full_service_name = 1;</code>
       */
      public Builder setFullServiceName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        fullServiceName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string full_service_name = 1;</code>
       */
      public Builder clearFullServiceName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        fullServiceName_ = getDefaultInstance().getFullServiceName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string full_service_name = 1;</code>
       */
      public Builder setFullServiceNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        fullServiceName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object methodName_ = "";
      /**
       * <code>optional string method_name = 2;</code>
       */
      public boolean hasMethodName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string method_name = 2;</code>
       */
      public java.lang.String getMethodName() {
        java.lang.Object ref = methodName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            methodName_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string method_name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getMethodNameBytes() {
        java.lang.Object ref = methodName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          methodName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string method_name = 2;</code>
       */
      public Builder setMethodName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        methodName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string method_name = 2;</code>
       */
      public Builder clearMethodName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        methodName_ = getDefaultInstance().getMethodName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string method_name = 2;</code>
       */
      public Builder setMethodNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        methodName_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString requestProto_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes request_proto = 3;</code>
       */
      public boolean hasRequestProto() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional bytes request_proto = 3;</code>
       */
      public com.google.protobuf.ByteString getRequestProto() {
        return requestProto_;
      }
      /**
       * <code>optional bytes request_proto = 3;</code>
       */
      public Builder setRequestProto(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        requestProto_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes request_proto = 3;</code>
       */
      public Builder clearRequestProto() {
        bitField0_ = (bitField0_ & ~0x00000004);
        requestProto_ = getDefaultInstance().getRequestProto();
        onChanged();
        return this;
      }

      private long requestId_ ;
      /**
       * <code>optional int64 request_id = 4;</code>
       */
      public boolean hasRequestId() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional int64 request_id = 4;</code>
       */
      public long getRequestId() {
        return requestId_;
      }
      /**
       * <code>optional int64 request_id = 4;</code>
       */
      public Builder setRequestId(long value) {
        bitField0_ |= 0x00000008;
        requestId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 request_id = 4;</code>
       */
      public Builder clearRequestId() {
        bitField0_ = (bitField0_ & ~0x00000008);
        requestId_ = 0L;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.orbekk.protobuf.Request)
    }

    // @@protoc_insertion_point(class_scope:com.orbekk.protobuf.Request)
    private static final com.orbekk.protobuf.Data.Request DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.orbekk.protobuf.Data.Request();
    }

    public static com.orbekk.protobuf.Data.Request getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Request>
        PARSER = new com.google.protobuf.AbstractParser<Request>() {
      public Request parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Request(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Request> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Request> getParserForType() {
      return PARSER;
    }

    public com.orbekk.protobuf.Data.Request getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.orbekk.protobuf.Response)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional bytes response_proto = 1;</code>
     */
    boolean hasResponseProto();
    /**
     * <code>optional bytes response_proto = 1;</code>
     */
    com.google.protobuf.ByteString getResponseProto();

    /**
     * <code>optional .com.orbekk.protobuf.Response.RpcError error = 2;</code>
     */
    boolean hasError();
    /**
     * <code>optional .com.orbekk.protobuf.Response.RpcError error = 2;</code>
     */
    com.orbekk.protobuf.Data.Response.RpcError getError();

    /**
     * <code>optional int64 request_id = 5;</code>
     */
    boolean hasRequestId();
    /**
     * <code>optional int64 request_id = 5;</code>
     */
    long getRequestId();

    /**
     * <pre>
     * Rpc status
     * </pre>
     *
     * <code>optional bool hasFailed = 4;</code>
     */
    boolean hasHasFailed();
    /**
     * <pre>
     * Rpc status
     * </pre>
     *
     * <code>optional bool hasFailed = 4;</code>
     */
    boolean getHasFailed();

    /**
     * <code>optional bool canceled = 6;</code>
     */
    boolean hasCanceled();
    /**
     * <code>optional bool canceled = 6;</code>
     */
    boolean getCanceled();

    /**
     * <code>optional bool done = 7;</code>
     */
    boolean hasDone();
    /**
     * <code>optional bool done = 7;</code>
     */
    boolean getDone();

    /**
     * <code>optional string error_text = 3;</code>
     */
    boolean hasErrorText();
    /**
     * <code>optional string error_text = 3;</code>
     */
    java.lang.String getErrorText();
    /**
     * <code>optional string error_text = 3;</code>
     */
    com.google.protobuf.ByteString
        getErrorTextBytes();
  }
  /**
   * <pre>
   * Next tag: 8
   * </pre>
   *
   * Protobuf type {@code com.orbekk.protobuf.Response}
   */
  public  static final class Response extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.orbekk.protobuf.Response)
      ResponseOrBuilder {
    // Use Response.newBuilder() to construct.
    private Response(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Response() {
      responseProto_ = com.google.protobuf.ByteString.EMPTY;
      error_ = 0;
      requestId_ = 0L;
      hasFailed_ = false;
      canceled_ = false;
      done_ = false;
      errorText_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Response(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              responseProto_ = input.readBytes();
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
              com.orbekk.protobuf.Data.Response.RpcError value = com.orbekk.protobuf.Data.Response.RpcError.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                bitField0_ |= 0x00000002;
                error_ = rawValue;
              }
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000040;
              errorText_ = bs;
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              hasFailed_ = input.readBool();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000004;
              requestId_ = input.readInt64();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000010;
              canceled_ = input.readBool();
              break;
            }
            case 56: {
              bitField0_ |= 0x00000020;
              done_ = input.readBool();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.orbekk.protobuf.Data.internal_static_com_orbekk_protobuf_Response_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.orbekk.protobuf.Data.internal_static_com_orbekk_protobuf_Response_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.orbekk.protobuf.Data.Response.class, com.orbekk.protobuf.Data.Response.Builder.class);
    }

    /**
     * Protobuf enum {@code com.orbekk.protobuf.Response.RpcError}
     */
    public enum RpcError
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>UNKNOWN_SERVICE = 0;</code>
       */
      UNKNOWN_SERVICE(0),
      /**
       * <code>UNKNOWN_METHOD = 1;</code>
       */
      UNKNOWN_METHOD(1),
      /**
       * <code>CANCELED = 2;</code>
       */
      CANCELED(2),
      /**
       * <code>INVALID_PROTOBUF = 3;</code>
       */
      INVALID_PROTOBUF(3),
      ;

      /**
       * <code>UNKNOWN_SERVICE = 0;</code>
       */
      public static final int UNKNOWN_SERVICE_VALUE = 0;
      /**
       * <code>UNKNOWN_METHOD = 1;</code>
       */
      public static final int UNKNOWN_METHOD_VALUE = 1;
      /**
       * <code>CANCELED = 2;</code>
       */
      public static final int CANCELED_VALUE = 2;
      /**
       * <code>INVALID_PROTOBUF = 3;</code>
       */
      public static final int INVALID_PROTOBUF_VALUE = 3;


      public final int getNumber() {
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static RpcError valueOf(int value) {
        return forNumber(value);
      }

      public static RpcError forNumber(int value) {
        switch (value) {
          case 0: return UNKNOWN_SERVICE;
          case 1: return UNKNOWN_METHOD;
          case 2: return CANCELED;
          case 3: return INVALID_PROTOBUF;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<RpcError>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          RpcError> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<RpcError>() {
              public RpcError findValueByNumber(int number) {
                return RpcError.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.orbekk.protobuf.Data.Response.getDescriptor().getEnumTypes().get(0);
      }

      private static final RpcError[] VALUES = values();

      public static RpcError valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private RpcError(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:com.orbekk.protobuf.Response.RpcError)
    }

    private int bitField0_;
    public static final int RESPONSE_PROTO_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString responseProto_;
    /**
     * <code>optional bytes response_proto = 1;</code>
     */
    public boolean hasResponseProto() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional bytes response_proto = 1;</code>
     */
    public com.google.protobuf.ByteString getResponseProto() {
      return responseProto_;
    }

    public static final int ERROR_FIELD_NUMBER = 2;
    private int error_;
    /**
     * <code>optional .com.orbekk.protobuf.Response.RpcError error = 2;</code>
     */
    public boolean hasError() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional .com.orbekk.protobuf.Response.RpcError error = 2;</code>
     */
    public com.orbekk.protobuf.Data.Response.RpcError getError() {
      com.orbekk.protobuf.Data.Response.RpcError result = com.orbekk.protobuf.Data.Response.RpcError.valueOf(error_);
      return result == null ? com.orbekk.protobuf.Data.Response.RpcError.UNKNOWN_SERVICE : result;
    }

    public static final int REQUEST_ID_FIELD_NUMBER = 5;
    private long requestId_;
    /**
     * <code>optional int64 request_id = 5;</code>
     */
    public boolean hasRequestId() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int64 request_id = 5;</code>
     */
    public long getRequestId() {
      return requestId_;
    }

    public static final int HASFAILED_FIELD_NUMBER = 4;
    private boolean hasFailed_;
    /**
     * <pre>
     * Rpc status
     * </pre>
     *
     * <code>optional bool hasFailed = 4;</code>
     */
    public boolean hasHasFailed() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <pre>
     * Rpc status
     * </pre>
     *
     * <code>optional bool hasFailed = 4;</code>
     */
    public boolean getHasFailed() {
      return hasFailed_;
    }

    public static final int CANCELED_FIELD_NUMBER = 6;
    private boolean canceled_;
    /**
     * <code>optional bool canceled = 6;</code>
     */
    public boolean hasCanceled() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional bool canceled = 6;</code>
     */
    public boolean getCanceled() {
      return canceled_;
    }

    public static final int DONE_FIELD_NUMBER = 7;
    private boolean done_;
    /**
     * <code>optional bool done = 7;</code>
     */
    public boolean hasDone() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional bool done = 7;</code>
     */
    public boolean getDone() {
      return done_;
    }

    public static final int ERROR_TEXT_FIELD_NUMBER = 3;
    private volatile java.lang.Object errorText_;
    /**
     * <code>optional string error_text = 3;</code>
     */
    public boolean hasErrorText() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional string error_text = 3;</code>
     */
    public java.lang.String getErrorText() {
      java.lang.Object ref = errorText_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          errorText_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string error_text = 3;</code>
     */
    public com.google.protobuf.ByteString
        getErrorTextBytes() {
      java.lang.Object ref = errorText_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        errorText_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, responseProto_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeEnum(2, error_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, errorText_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBool(4, hasFailed_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt64(5, requestId_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBool(6, canceled_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBool(7, done_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, responseProto_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, error_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, errorText_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(4, hasFailed_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(5, requestId_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(6, canceled_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(7, done_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.orbekk.protobuf.Data.Response)) {
        return super.equals(obj);
      }
      com.orbekk.protobuf.Data.Response other = (com.orbekk.protobuf.Data.Response) obj;

      boolean result = true;
      result = result && (hasResponseProto() == other.hasResponseProto());
      if (hasResponseProto()) {
        result = result && getResponseProto()
            .equals(other.getResponseProto());
      }
      result = result && (hasError() == other.hasError());
      if (hasError()) {
        result = result && error_ == other.error_;
      }
      result = result && (hasRequestId() == other.hasRequestId());
      if (hasRequestId()) {
        result = result && (getRequestId()
            == other.getRequestId());
      }
      result = result && (hasHasFailed() == other.hasHasFailed());
      if (hasHasFailed()) {
        result = result && (getHasFailed()
            == other.getHasFailed());
      }
      result = result && (hasCanceled() == other.hasCanceled());
      if (hasCanceled()) {
        result = result && (getCanceled()
            == other.getCanceled());
      }
      result = result && (hasDone() == other.hasDone());
      if (hasDone()) {
        result = result && (getDone()
            == other.getDone());
      }
      result = result && (hasErrorText() == other.hasErrorText());
      if (hasErrorText()) {
        result = result && getErrorText()
            .equals(other.getErrorText());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasResponseProto()) {
        hash = (37 * hash) + RESPONSE_PROTO_FIELD_NUMBER;
        hash = (53 * hash) + getResponseProto().hashCode();
      }
      if (hasError()) {
        hash = (37 * hash) + ERROR_FIELD_NUMBER;
        hash = (53 * hash) + error_;
      }
      if (hasRequestId()) {
        hash = (37 * hash) + REQUEST_ID_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getRequestId());
      }
      if (hasHasFailed()) {
        hash = (37 * hash) + HASFAILED_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getHasFailed());
      }
      if (hasCanceled()) {
        hash = (37 * hash) + CANCELED_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getCanceled());
      }
      if (hasDone()) {
        hash = (37 * hash) + DONE_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getDone());
      }
      if (hasErrorText()) {
        hash = (37 * hash) + ERROR_TEXT_FIELD_NUMBER;
        hash = (53 * hash) + getErrorText().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.orbekk.protobuf.Data.Response parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.orbekk.protobuf.Data.Response parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.orbekk.protobuf.Data.Response parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.orbekk.protobuf.Data.Response parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.orbekk.protobuf.Data.Response parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.orbekk.protobuf.Data.Response parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.orbekk.protobuf.Data.Response parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.orbekk.protobuf.Data.Response parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.orbekk.protobuf.Data.Response parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.orbekk.protobuf.Data.Response parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.orbekk.protobuf.Data.Response prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Next tag: 8
     * </pre>
     *
     * Protobuf type {@code com.orbekk.protobuf.Response}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.orbekk.protobuf.Response)
        com.orbekk.protobuf.Data.ResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.orbekk.protobuf.Data.internal_static_com_orbekk_protobuf_Response_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.orbekk.protobuf.Data.internal_static_com_orbekk_protobuf_Response_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.orbekk.protobuf.Data.Response.class, com.orbekk.protobuf.Data.Response.Builder.class);
      }

      // Construct using com.orbekk.protobuf.Data.Response.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        responseProto_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        error_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        requestId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        hasFailed_ = false;
        bitField0_ = (bitField0_ & ~0x00000008);
        canceled_ = false;
        bitField0_ = (bitField0_ & ~0x00000010);
        done_ = false;
        bitField0_ = (bitField0_ & ~0x00000020);
        errorText_ = "";
        bitField0_ = (bitField0_ & ~0x00000040);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.orbekk.protobuf.Data.internal_static_com_orbekk_protobuf_Response_descriptor;
      }

      public com.orbekk.protobuf.Data.Response getDefaultInstanceForType() {
        return com.orbekk.protobuf.Data.Response.getDefaultInstance();
      }

      public com.orbekk.protobuf.Data.Response build() {
        com.orbekk.protobuf.Data.Response result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.orbekk.protobuf.Data.Response buildPartial() {
        com.orbekk.protobuf.Data.Response result = new com.orbekk.protobuf.Data.Response(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.responseProto_ = responseProto_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.error_ = error_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.requestId_ = requestId_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.hasFailed_ = hasFailed_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.canceled_ = canceled_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.done_ = done_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.errorText_ = errorText_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.orbekk.protobuf.Data.Response) {
          return mergeFrom((com.orbekk.protobuf.Data.Response)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.orbekk.protobuf.Data.Response other) {
        if (other == com.orbekk.protobuf.Data.Response.getDefaultInstance()) return this;
        if (other.hasResponseProto()) {
          setResponseProto(other.getResponseProto());
        }
        if (other.hasError()) {
          setError(other.getError());
        }
        if (other.hasRequestId()) {
          setRequestId(other.getRequestId());
        }
        if (other.hasHasFailed()) {
          setHasFailed(other.getHasFailed());
        }
        if (other.hasCanceled()) {
          setCanceled(other.getCanceled());
        }
        if (other.hasDone()) {
          setDone(other.getDone());
        }
        if (other.hasErrorText()) {
          bitField0_ |= 0x00000040;
          errorText_ = other.errorText_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.orbekk.protobuf.Data.Response parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.orbekk.protobuf.Data.Response) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.ByteString responseProto_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes response_proto = 1;</code>
       */
      public boolean hasResponseProto() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional bytes response_proto = 1;</code>
       */
      public com.google.protobuf.ByteString getResponseProto() {
        return responseProto_;
      }
      /**
       * <code>optional bytes response_proto = 1;</code>
       */
      public Builder setResponseProto(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        responseProto_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes response_proto = 1;</code>
       */
      public Builder clearResponseProto() {
        bitField0_ = (bitField0_ & ~0x00000001);
        responseProto_ = getDefaultInstance().getResponseProto();
        onChanged();
        return this;
      }

      private int error_ = 0;
      /**
       * <code>optional .com.orbekk.protobuf.Response.RpcError error = 2;</code>
       */
      public boolean hasError() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional .com.orbekk.protobuf.Response.RpcError error = 2;</code>
       */
      public com.orbekk.protobuf.Data.Response.RpcError getError() {
        com.orbekk.protobuf.Data.Response.RpcError result = com.orbekk.protobuf.Data.Response.RpcError.valueOf(error_);
        return result == null ? com.orbekk.protobuf.Data.Response.RpcError.UNKNOWN_SERVICE : result;
      }
      /**
       * <code>optional .com.orbekk.protobuf.Response.RpcError error = 2;</code>
       */
      public Builder setError(com.orbekk.protobuf.Data.Response.RpcError value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        error_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>optional .com.orbekk.protobuf.Response.RpcError error = 2;</code>
       */
      public Builder clearError() {
        bitField0_ = (bitField0_ & ~0x00000002);
        error_ = 0;
        onChanged();
        return this;
      }

      private long requestId_ ;
      /**
       * <code>optional int64 request_id = 5;</code>
       */
      public boolean hasRequestId() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int64 request_id = 5;</code>
       */
      public long getRequestId() {
        return requestId_;
      }
      /**
       * <code>optional int64 request_id = 5;</code>
       */
      public Builder setRequestId(long value) {
        bitField0_ |= 0x00000004;
        requestId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 request_id = 5;</code>
       */
      public Builder clearRequestId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        requestId_ = 0L;
        onChanged();
        return this;
      }

      private boolean hasFailed_ ;
      /**
       * <pre>
       * Rpc status
       * </pre>
       *
       * <code>optional bool hasFailed = 4;</code>
       */
      public boolean hasHasFailed() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <pre>
       * Rpc status
       * </pre>
       *
       * <code>optional bool hasFailed = 4;</code>
       */
      public boolean getHasFailed() {
        return hasFailed_;
      }
      /**
       * <pre>
       * Rpc status
       * </pre>
       *
       * <code>optional bool hasFailed = 4;</code>
       */
      public Builder setHasFailed(boolean value) {
        bitField0_ |= 0x00000008;
        hasFailed_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Rpc status
       * </pre>
       *
       * <code>optional bool hasFailed = 4;</code>
       */
      public Builder clearHasFailed() {
        bitField0_ = (bitField0_ & ~0x00000008);
        hasFailed_ = false;
        onChanged();
        return this;
      }

      private boolean canceled_ ;
      /**
       * <code>optional bool canceled = 6;</code>
       */
      public boolean hasCanceled() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional bool canceled = 6;</code>
       */
      public boolean getCanceled() {
        return canceled_;
      }
      /**
       * <code>optional bool canceled = 6;</code>
       */
      public Builder setCanceled(boolean value) {
        bitField0_ |= 0x00000010;
        canceled_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool canceled = 6;</code>
       */
      public Builder clearCanceled() {
        bitField0_ = (bitField0_ & ~0x00000010);
        canceled_ = false;
        onChanged();
        return this;
      }

      private boolean done_ ;
      /**
       * <code>optional bool done = 7;</code>
       */
      public boolean hasDone() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional bool done = 7;</code>
       */
      public boolean getDone() {
        return done_;
      }
      /**
       * <code>optional bool done = 7;</code>
       */
      public Builder setDone(boolean value) {
        bitField0_ |= 0x00000020;
        done_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool done = 7;</code>
       */
      public Builder clearDone() {
        bitField0_ = (bitField0_ & ~0x00000020);
        done_ = false;
        onChanged();
        return this;
      }

      private java.lang.Object errorText_ = "";
      /**
       * <code>optional string error_text = 3;</code>
       */
      public boolean hasErrorText() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional string error_text = 3;</code>
       */
      public java.lang.String getErrorText() {
        java.lang.Object ref = errorText_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            errorText_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string error_text = 3;</code>
       */
      public com.google.protobuf.ByteString
          getErrorTextBytes() {
        java.lang.Object ref = errorText_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          errorText_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string error_text = 3;</code>
       */
      public Builder setErrorText(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        errorText_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string error_text = 3;</code>
       */
      public Builder clearErrorText() {
        bitField0_ = (bitField0_ & ~0x00000040);
        errorText_ = getDefaultInstance().getErrorText();
        onChanged();
        return this;
      }
      /**
       * <code>optional string error_text = 3;</code>
       */
      public Builder setErrorTextBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        errorText_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.orbekk.protobuf.Response)
    }

    // @@protoc_insertion_point(class_scope:com.orbekk.protobuf.Response)
    private static final com.orbekk.protobuf.Data.Response DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.orbekk.protobuf.Data.Response();
    }

    public static com.orbekk.protobuf.Data.Response getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Response>
        PARSER = new com.google.protobuf.AbstractParser<Response>() {
      public Response parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Response(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Response> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Response> getParserForType() {
      return PARSER;
    }

    public com.orbekk.protobuf.Data.Response getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_orbekk_protobuf_Request_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_orbekk_protobuf_Request_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_orbekk_protobuf_Response_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_orbekk_protobuf_Response_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n,src/main/java/com/orbekk/protobuf/Data" +
      ".proto\022\023com.orbekk.protobuf\"d\n\007Request\022\031" +
      "\n\021full_service_name\030\001 \001(\t\022\023\n\013method_name" +
      "\030\002 \001(\t\022\025\n\rrequest_proto\030\003 \001(\014\022\022\n\nrequest" +
      "_id\030\004 \001(\003\"\215\002\n\010Response\022\026\n\016response_proto" +
      "\030\001 \001(\014\0225\n\005error\030\002 \001(\0162&.com.orbekk.proto" +
      "buf.Response.RpcError\022\022\n\nrequest_id\030\005 \001(" +
      "\003\022\021\n\thasFailed\030\004 \001(\010\022\020\n\010canceled\030\006 \001(\010\022\014" +
      "\n\004done\030\007 \001(\010\022\022\n\nerror_text\030\003 \001(\t\"W\n\010RpcE" +
      "rror\022\023\n\017UNKNOWN_SERVICE\020\000\022\022\n\016UNKNOWN_MET",
      "HOD\020\001\022\014\n\010CANCELED\020\002\022\024\n\020INVALID_PROTOBUF\020" +
      "\003"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_orbekk_protobuf_Request_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_orbekk_protobuf_Request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_orbekk_protobuf_Request_descriptor,
        new java.lang.String[] { "FullServiceName", "MethodName", "RequestProto", "RequestId", });
    internal_static_com_orbekk_protobuf_Response_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_orbekk_protobuf_Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_orbekk_protobuf_Response_descriptor,
        new java.lang.String[] { "ResponseProto", "Error", "RequestId", "HasFailed", "Canceled", "Done", "ErrorText", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
