// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CTR.proto

package com.orbekk.example;

public final class CTR {
  private CTR() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface RequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.orbekk.example.Request)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int64 guid = 1;</code>
     */
    long getGuid();

    /**
     * <code>optional int32 bannerid = 2;</code>
     */
    int getBannerid();
  }
  /**
   * Protobuf type {@code com.orbekk.example.Request}
   */
  public  static final class Request extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.orbekk.example.Request)
      RequestOrBuilder {
    // Use Request.newBuilder() to construct.
    private Request(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Request() {
      guid_ = 0L;
      bannerid_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Request(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              guid_ = input.readInt64();
              break;
            }
            case 16: {

              bannerid_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.orbekk.example.CTR.internal_static_com_orbekk_example_Request_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.orbekk.example.CTR.internal_static_com_orbekk_example_Request_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.orbekk.example.CTR.Request.class, com.orbekk.example.CTR.Request.Builder.class);
    }

    public static final int GUID_FIELD_NUMBER = 1;
    private long guid_;
    /**
     * <code>optional int64 guid = 1;</code>
     */
    public long getGuid() {
      return guid_;
    }

    public static final int BANNERID_FIELD_NUMBER = 2;
    private int bannerid_;
    /**
     * <code>optional int32 bannerid = 2;</code>
     */
    public int getBannerid() {
      return bannerid_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (guid_ != 0L) {
        output.writeInt64(1, guid_);
      }
      if (bannerid_ != 0) {
        output.writeInt32(2, bannerid_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (guid_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, guid_);
      }
      if (bannerid_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, bannerid_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.orbekk.example.CTR.Request)) {
        return super.equals(obj);
      }
      com.orbekk.example.CTR.Request other = (com.orbekk.example.CTR.Request) obj;

      boolean result = true;
      result = result && (getGuid()
          == other.getGuid());
      result = result && (getBannerid()
          == other.getBannerid());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + GUID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getGuid());
      hash = (37 * hash) + BANNERID_FIELD_NUMBER;
      hash = (53 * hash) + getBannerid();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.orbekk.example.CTR.Request parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.orbekk.example.CTR.Request parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.orbekk.example.CTR.Request parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.orbekk.example.CTR.Request parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.orbekk.example.CTR.Request parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.orbekk.example.CTR.Request parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.orbekk.example.CTR.Request parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.orbekk.example.CTR.Request parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.orbekk.example.CTR.Request parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.orbekk.example.CTR.Request parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.orbekk.example.CTR.Request prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.orbekk.example.Request}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.orbekk.example.Request)
        com.orbekk.example.CTR.RequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.orbekk.example.CTR.internal_static_com_orbekk_example_Request_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.orbekk.example.CTR.internal_static_com_orbekk_example_Request_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.orbekk.example.CTR.Request.class, com.orbekk.example.CTR.Request.Builder.class);
      }

      // Construct using com.orbekk.example.CTR.Request.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        guid_ = 0L;

        bannerid_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.orbekk.example.CTR.internal_static_com_orbekk_example_Request_descriptor;
      }

      public com.orbekk.example.CTR.Request getDefaultInstanceForType() {
        return com.orbekk.example.CTR.Request.getDefaultInstance();
      }

      public com.orbekk.example.CTR.Request build() {
        com.orbekk.example.CTR.Request result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.orbekk.example.CTR.Request buildPartial() {
        com.orbekk.example.CTR.Request result = new com.orbekk.example.CTR.Request(this);
        result.guid_ = guid_;
        result.bannerid_ = bannerid_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.orbekk.example.CTR.Request) {
          return mergeFrom((com.orbekk.example.CTR.Request)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.orbekk.example.CTR.Request other) {
        if (other == com.orbekk.example.CTR.Request.getDefaultInstance()) return this;
        if (other.getGuid() != 0L) {
          setGuid(other.getGuid());
        }
        if (other.getBannerid() != 0) {
          setBannerid(other.getBannerid());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.orbekk.example.CTR.Request parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.orbekk.example.CTR.Request) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long guid_ ;
      /**
       * <code>optional int64 guid = 1;</code>
       */
      public long getGuid() {
        return guid_;
      }
      /**
       * <code>optional int64 guid = 1;</code>
       */
      public Builder setGuid(long value) {
        
        guid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 guid = 1;</code>
       */
      public Builder clearGuid() {
        
        guid_ = 0L;
        onChanged();
        return this;
      }

      private int bannerid_ ;
      /**
       * <code>optional int32 bannerid = 2;</code>
       */
      public int getBannerid() {
        return bannerid_;
      }
      /**
       * <code>optional int32 bannerid = 2;</code>
       */
      public Builder setBannerid(int value) {
        
        bannerid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 bannerid = 2;</code>
       */
      public Builder clearBannerid() {
        
        bannerid_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.orbekk.example.Request)
    }

    // @@protoc_insertion_point(class_scope:com.orbekk.example.Request)
    private static final com.orbekk.example.CTR.Request DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.orbekk.example.CTR.Request();
    }

    public static com.orbekk.example.CTR.Request getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Request>
        PARSER = new com.google.protobuf.AbstractParser<Request>() {
      public Request parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Request(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Request> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Request> getParserForType() {
      return PARSER;
    }

    public com.orbekk.example.CTR.Request getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.orbekk.example.Response)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 bannerid = 1;</code>
     */
    int getBannerid();

    /**
     * <code>optional float ctrPred = 2;</code>
     */
    float getCtrPred();
  }
  /**
   * Protobuf type {@code com.orbekk.example.Response}
   */
  public  static final class Response extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.orbekk.example.Response)
      ResponseOrBuilder {
    // Use Response.newBuilder() to construct.
    private Response(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Response() {
      bannerid_ = 0;
      ctrPred_ = 0F;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Response(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              bannerid_ = input.readInt32();
              break;
            }
            case 21: {

              ctrPred_ = input.readFloat();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.orbekk.example.CTR.internal_static_com_orbekk_example_Response_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.orbekk.example.CTR.internal_static_com_orbekk_example_Response_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.orbekk.example.CTR.Response.class, com.orbekk.example.CTR.Response.Builder.class);
    }

    public static final int BANNERID_FIELD_NUMBER = 1;
    private int bannerid_;
    /**
     * <code>optional int32 bannerid = 1;</code>
     */
    public int getBannerid() {
      return bannerid_;
    }

    public static final int CTRPRED_FIELD_NUMBER = 2;
    private float ctrPred_;
    /**
     * <code>optional float ctrPred = 2;</code>
     */
    public float getCtrPred() {
      return ctrPred_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (bannerid_ != 0) {
        output.writeInt32(1, bannerid_);
      }
      if (ctrPred_ != 0F) {
        output.writeFloat(2, ctrPred_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (bannerid_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, bannerid_);
      }
      if (ctrPred_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(2, ctrPred_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.orbekk.example.CTR.Response)) {
        return super.equals(obj);
      }
      com.orbekk.example.CTR.Response other = (com.orbekk.example.CTR.Response) obj;

      boolean result = true;
      result = result && (getBannerid()
          == other.getBannerid());
      result = result && (
          java.lang.Float.floatToIntBits(getCtrPred())
          == java.lang.Float.floatToIntBits(
              other.getCtrPred()));
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + BANNERID_FIELD_NUMBER;
      hash = (53 * hash) + getBannerid();
      hash = (37 * hash) + CTRPRED_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getCtrPred());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.orbekk.example.CTR.Response parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.orbekk.example.CTR.Response parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.orbekk.example.CTR.Response parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.orbekk.example.CTR.Response parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.orbekk.example.CTR.Response parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.orbekk.example.CTR.Response parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.orbekk.example.CTR.Response parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.orbekk.example.CTR.Response parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.orbekk.example.CTR.Response parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.orbekk.example.CTR.Response parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.orbekk.example.CTR.Response prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.orbekk.example.Response}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.orbekk.example.Response)
        com.orbekk.example.CTR.ResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.orbekk.example.CTR.internal_static_com_orbekk_example_Response_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.orbekk.example.CTR.internal_static_com_orbekk_example_Response_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.orbekk.example.CTR.Response.class, com.orbekk.example.CTR.Response.Builder.class);
      }

      // Construct using com.orbekk.example.CTR.Response.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        bannerid_ = 0;

        ctrPred_ = 0F;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.orbekk.example.CTR.internal_static_com_orbekk_example_Response_descriptor;
      }

      public com.orbekk.example.CTR.Response getDefaultInstanceForType() {
        return com.orbekk.example.CTR.Response.getDefaultInstance();
      }

      public com.orbekk.example.CTR.Response build() {
        com.orbekk.example.CTR.Response result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.orbekk.example.CTR.Response buildPartial() {
        com.orbekk.example.CTR.Response result = new com.orbekk.example.CTR.Response(this);
        result.bannerid_ = bannerid_;
        result.ctrPred_ = ctrPred_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.orbekk.example.CTR.Response) {
          return mergeFrom((com.orbekk.example.CTR.Response)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.orbekk.example.CTR.Response other) {
        if (other == com.orbekk.example.CTR.Response.getDefaultInstance()) return this;
        if (other.getBannerid() != 0) {
          setBannerid(other.getBannerid());
        }
        if (other.getCtrPred() != 0F) {
          setCtrPred(other.getCtrPred());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.orbekk.example.CTR.Response parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.orbekk.example.CTR.Response) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int bannerid_ ;
      /**
       * <code>optional int32 bannerid = 1;</code>
       */
      public int getBannerid() {
        return bannerid_;
      }
      /**
       * <code>optional int32 bannerid = 1;</code>
       */
      public Builder setBannerid(int value) {
        
        bannerid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 bannerid = 1;</code>
       */
      public Builder clearBannerid() {
        
        bannerid_ = 0;
        onChanged();
        return this;
      }

      private float ctrPred_ ;
      /**
       * <code>optional float ctrPred = 2;</code>
       */
      public float getCtrPred() {
        return ctrPred_;
      }
      /**
       * <code>optional float ctrPred = 2;</code>
       */
      public Builder setCtrPred(float value) {
        
        ctrPred_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional float ctrPred = 2;</code>
       */
      public Builder clearCtrPred() {
        
        ctrPred_ = 0F;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.orbekk.example.Response)
    }

    // @@protoc_insertion_point(class_scope:com.orbekk.example.Response)
    private static final com.orbekk.example.CTR.Response DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.orbekk.example.CTR.Response();
    }

    public static com.orbekk.example.CTR.Response getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Response>
        PARSER = new com.google.protobuf.AbstractParser<Response>() {
      public Response parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Response(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Response> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Response> getParserForType() {
      return PARSER;
    }

    public com.orbekk.example.CTR.Response getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  /**
   * Protobuf service {@code com.orbekk.example.CTRPredictionService}
   */
  public static abstract class CTRPredictionService
      implements com.google.protobuf.Service {
    protected CTRPredictionService() {}

    public interface Interface {
      /**
       * <code>rpc GetPrediction(.com.orbekk.example.Request) returns (.com.orbekk.example.Response);</code>
       */
      public abstract void getPrediction(
          com.google.protobuf.RpcController controller,
          com.orbekk.example.CTR.Request request,
          com.google.protobuf.RpcCallback<com.orbekk.example.CTR.Response> done);

    }

    public static com.google.protobuf.Service newReflectiveService(
        final Interface impl) {
      return new CTRPredictionService() {
        @java.lang.Override
        public  void getPrediction(
            com.google.protobuf.RpcController controller,
            com.orbekk.example.CTR.Request request,
            com.google.protobuf.RpcCallback<com.orbekk.example.CTR.Response> done) {
          impl.getPrediction(controller, request, done);
        }

      };
    }

    public static com.google.protobuf.BlockingService
        newReflectiveBlockingService(final BlockingInterface impl) {
      return new com.google.protobuf.BlockingService() {
        public final com.google.protobuf.Descriptors.ServiceDescriptor
            getDescriptorForType() {
          return getDescriptor();
        }

        public final com.google.protobuf.Message callBlockingMethod(
            com.google.protobuf.Descriptors.MethodDescriptor method,
            com.google.protobuf.RpcController controller,
            com.google.protobuf.Message request)
            throws com.google.protobuf.ServiceException {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.callBlockingMethod() given method descriptor for " +
              "wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return impl.getPrediction(controller, (com.orbekk.example.CTR.Request)request);
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

        public final com.google.protobuf.Message
            getRequestPrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getRequestPrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return com.orbekk.example.CTR.Request.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

        public final com.google.protobuf.Message
            getResponsePrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getResponsePrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return com.orbekk.example.CTR.Response.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

      };
    }

    /**
     * <code>rpc GetPrediction(.com.orbekk.example.Request) returns (.com.orbekk.example.Response);</code>
     */
    public abstract void getPrediction(
        com.google.protobuf.RpcController controller,
        com.orbekk.example.CTR.Request request,
        com.google.protobuf.RpcCallback<com.orbekk.example.CTR.Response> done);

    public static final
        com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptor() {
      return com.orbekk.example.CTR.getDescriptor().getServices().get(0);
    }
    public final com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }

    public final void callMethod(
        com.google.protobuf.Descriptors.MethodDescriptor method,
        com.google.protobuf.RpcController controller,
        com.google.protobuf.Message request,
        com.google.protobuf.RpcCallback<
          com.google.protobuf.Message> done) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.callMethod() given method descriptor for wrong " +
          "service type.");
      }
      switch(method.getIndex()) {
        case 0:
          this.getPrediction(controller, (com.orbekk.example.CTR.Request)request,
            com.google.protobuf.RpcUtil.<com.orbekk.example.CTR.Response>specializeCallback(
              done));
          return;
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public final com.google.protobuf.Message
        getRequestPrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getRequestPrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return com.orbekk.example.CTR.Request.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public final com.google.protobuf.Message
        getResponsePrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getResponsePrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return com.orbekk.example.CTR.Response.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public static Stub newStub(
        com.google.protobuf.RpcChannel channel) {
      return new Stub(channel);
    }

    public static final class Stub extends com.orbekk.example.CTR.CTRPredictionService implements Interface {
      private Stub(com.google.protobuf.RpcChannel channel) {
        this.channel = channel;
      }

      private final com.google.protobuf.RpcChannel channel;

      public com.google.protobuf.RpcChannel getChannel() {
        return channel;
      }

      public  void getPrediction(
          com.google.protobuf.RpcController controller,
          com.orbekk.example.CTR.Request request,
          com.google.protobuf.RpcCallback<com.orbekk.example.CTR.Response> done) {
        channel.callMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          com.orbekk.example.CTR.Response.getDefaultInstance(),
          com.google.protobuf.RpcUtil.generalizeCallback(
            done,
            com.orbekk.example.CTR.Response.class,
            com.orbekk.example.CTR.Response.getDefaultInstance()));
      }
    }

    public static BlockingInterface newBlockingStub(
        com.google.protobuf.BlockingRpcChannel channel) {
      return new BlockingStub(channel);
    }

    public interface BlockingInterface {
      public com.orbekk.example.CTR.Response getPrediction(
          com.google.protobuf.RpcController controller,
          com.orbekk.example.CTR.Request request)
          throws com.google.protobuf.ServiceException;
    }

    private static final class BlockingStub implements BlockingInterface {
      private BlockingStub(com.google.protobuf.BlockingRpcChannel channel) {
        this.channel = channel;
      }

      private final com.google.protobuf.BlockingRpcChannel channel;

      public com.orbekk.example.CTR.Response getPrediction(
          com.google.protobuf.RpcController controller,
          com.orbekk.example.CTR.Request request)
          throws com.google.protobuf.ServiceException {
        return (com.orbekk.example.CTR.Response) channel.callBlockingMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          com.orbekk.example.CTR.Response.getDefaultInstance());
      }

    }

    // @@protoc_insertion_point(class_scope:com.orbekk.example.CTRPredictionService)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_orbekk_example_Request_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_orbekk_example_Request_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_orbekk_example_Response_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_orbekk_example_Response_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tCTR.proto\022\022com.orbekk.example\")\n\007Reque" +
      "st\022\014\n\004guid\030\001 \001(\003\022\020\n\010bannerid\030\002 \001(\005\"-\n\010Re" +
      "sponse\022\020\n\010bannerid\030\001 \001(\005\022\017\n\007ctrPred\030\002 \001(" +
      "\0022b\n\024CTRPredictionService\022J\n\rGetPredicti" +
      "on\022\033.com.orbekk.example.Request\032\034.com.or" +
      "bekk.example.ResponseB\003\210\001\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_orbekk_example_Request_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_orbekk_example_Request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_orbekk_example_Request_descriptor,
        new java.lang.String[] { "Guid", "Bannerid", });
    internal_static_com_orbekk_example_Response_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_orbekk_example_Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_orbekk_example_Response_descriptor,
        new java.lang.String[] { "Bannerid", "CtrPred", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
