// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CTR.proto

package com.orbekk.example;

public final class CTR {
  private CTR() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface RequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.orbekk.example.Request)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 weekday = 1;</code>
     */
    int getWeekday();

    /**
     * <code>optional int32 hour = 2;</code>
     */
    int getHour();

    /**
     * <code>optional int32 bannerId = 3;</code>
     */
    int getBannerId();

    /**
     * <code>optional int32 geographic = 4;</code>
     */
    int getGeographic();

    /**
     * <code>optional int32 zoneId = 5;</code>
     */
    int getZoneId();

    /**
     * <code>optional int64 guid = 6;</code>
     */
    long getGuid();

    /**
     * <code>optional string domain = 7;</code>
     */
    java.lang.String getDomain();
    /**
     * <code>optional string domain = 7;</code>
     */
    com.google.protobuf.ByteString
        getDomainBytes();

    /**
     * <code>optional int32 osCode = 8;</code>
     */
    int getOsCode();

    /**
     * <code>optional int32 browserCode = 9;</code>
     */
    int getBrowserCode();
  }
  /**
   * Protobuf type {@code com.orbekk.example.Request}
   */
  public  static final class Request extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.orbekk.example.Request)
      RequestOrBuilder {
    // Use Request.newBuilder() to construct.
    private Request(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Request() {
      weekday_ = 0;
      hour_ = 0;
      bannerId_ = 0;
      geographic_ = 0;
      zoneId_ = 0;
      guid_ = 0L;
      domain_ = "";
      osCode_ = 0;
      browserCode_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Request(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              weekday_ = input.readInt32();
              break;
            }
            case 16: {

              hour_ = input.readInt32();
              break;
            }
            case 24: {

              bannerId_ = input.readInt32();
              break;
            }
            case 32: {

              geographic_ = input.readInt32();
              break;
            }
            case 40: {

              zoneId_ = input.readInt32();
              break;
            }
            case 48: {

              guid_ = input.readInt64();
              break;
            }
            case 58: {
              java.lang.String s = input.readStringRequireUtf8();

              domain_ = s;
              break;
            }
            case 64: {

              osCode_ = input.readInt32();
              break;
            }
            case 72: {

              browserCode_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.orbekk.example.CTR.internal_static_com_orbekk_example_Request_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.orbekk.example.CTR.internal_static_com_orbekk_example_Request_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.orbekk.example.CTR.Request.class, com.orbekk.example.CTR.Request.Builder.class);
    }

    public static final int WEEKDAY_FIELD_NUMBER = 1;
    private int weekday_;
    /**
     * <code>optional int32 weekday = 1;</code>
     */
    public int getWeekday() {
      return weekday_;
    }

    public static final int HOUR_FIELD_NUMBER = 2;
    private int hour_;
    /**
     * <code>optional int32 hour = 2;</code>
     */
    public int getHour() {
      return hour_;
    }

    public static final int BANNERID_FIELD_NUMBER = 3;
    private int bannerId_;
    /**
     * <code>optional int32 bannerId = 3;</code>
     */
    public int getBannerId() {
      return bannerId_;
    }

    public static final int GEOGRAPHIC_FIELD_NUMBER = 4;
    private int geographic_;
    /**
     * <code>optional int32 geographic = 4;</code>
     */
    public int getGeographic() {
      return geographic_;
    }

    public static final int ZONEID_FIELD_NUMBER = 5;
    private int zoneId_;
    /**
     * <code>optional int32 zoneId = 5;</code>
     */
    public int getZoneId() {
      return zoneId_;
    }

    public static final int GUID_FIELD_NUMBER = 6;
    private long guid_;
    /**
     * <code>optional int64 guid = 6;</code>
     */
    public long getGuid() {
      return guid_;
    }

    public static final int DOMAIN_FIELD_NUMBER = 7;
    private volatile java.lang.Object domain_;
    /**
     * <code>optional string domain = 7;</code>
     */
    public java.lang.String getDomain() {
      java.lang.Object ref = domain_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        domain_ = s;
        return s;
      }
    }
    /**
     * <code>optional string domain = 7;</code>
     */
    public com.google.protobuf.ByteString
        getDomainBytes() {
      java.lang.Object ref = domain_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        domain_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int OSCODE_FIELD_NUMBER = 8;
    private int osCode_;
    /**
     * <code>optional int32 osCode = 8;</code>
     */
    public int getOsCode() {
      return osCode_;
    }

    public static final int BROWSERCODE_FIELD_NUMBER = 9;
    private int browserCode_;
    /**
     * <code>optional int32 browserCode = 9;</code>
     */
    public int getBrowserCode() {
      return browserCode_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (weekday_ != 0) {
        output.writeInt32(1, weekday_);
      }
      if (hour_ != 0) {
        output.writeInt32(2, hour_);
      }
      if (bannerId_ != 0) {
        output.writeInt32(3, bannerId_);
      }
      if (geographic_ != 0) {
        output.writeInt32(4, geographic_);
      }
      if (zoneId_ != 0) {
        output.writeInt32(5, zoneId_);
      }
      if (guid_ != 0L) {
        output.writeInt64(6, guid_);
      }
      if (!getDomainBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, domain_);
      }
      if (osCode_ != 0) {
        output.writeInt32(8, osCode_);
      }
      if (browserCode_ != 0) {
        output.writeInt32(9, browserCode_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (weekday_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, weekday_);
      }
      if (hour_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, hour_);
      }
      if (bannerId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, bannerId_);
      }
      if (geographic_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, geographic_);
      }
      if (zoneId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, zoneId_);
      }
      if (guid_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(6, guid_);
      }
      if (!getDomainBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, domain_);
      }
      if (osCode_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(8, osCode_);
      }
      if (browserCode_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(9, browserCode_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.orbekk.example.CTR.Request)) {
        return super.equals(obj);
      }
      com.orbekk.example.CTR.Request other = (com.orbekk.example.CTR.Request) obj;

      boolean result = true;
      result = result && (getWeekday()
          == other.getWeekday());
      result = result && (getHour()
          == other.getHour());
      result = result && (getBannerId()
          == other.getBannerId());
      result = result && (getGeographic()
          == other.getGeographic());
      result = result && (getZoneId()
          == other.getZoneId());
      result = result && (getGuid()
          == other.getGuid());
      result = result && getDomain()
          .equals(other.getDomain());
      result = result && (getOsCode()
          == other.getOsCode());
      result = result && (getBrowserCode()
          == other.getBrowserCode());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + WEEKDAY_FIELD_NUMBER;
      hash = (53 * hash) + getWeekday();
      hash = (37 * hash) + HOUR_FIELD_NUMBER;
      hash = (53 * hash) + getHour();
      hash = (37 * hash) + BANNERID_FIELD_NUMBER;
      hash = (53 * hash) + getBannerId();
      hash = (37 * hash) + GEOGRAPHIC_FIELD_NUMBER;
      hash = (53 * hash) + getGeographic();
      hash = (37 * hash) + ZONEID_FIELD_NUMBER;
      hash = (53 * hash) + getZoneId();
      hash = (37 * hash) + GUID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getGuid());
      hash = (37 * hash) + DOMAIN_FIELD_NUMBER;
      hash = (53 * hash) + getDomain().hashCode();
      hash = (37 * hash) + OSCODE_FIELD_NUMBER;
      hash = (53 * hash) + getOsCode();
      hash = (37 * hash) + BROWSERCODE_FIELD_NUMBER;
      hash = (53 * hash) + getBrowserCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.orbekk.example.CTR.Request parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.orbekk.example.CTR.Request parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.orbekk.example.CTR.Request parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.orbekk.example.CTR.Request parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.orbekk.example.CTR.Request parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.orbekk.example.CTR.Request parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.orbekk.example.CTR.Request parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.orbekk.example.CTR.Request parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.orbekk.example.CTR.Request parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.orbekk.example.CTR.Request parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.orbekk.example.CTR.Request prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.orbekk.example.Request}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.orbekk.example.Request)
        com.orbekk.example.CTR.RequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.orbekk.example.CTR.internal_static_com_orbekk_example_Request_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.orbekk.example.CTR.internal_static_com_orbekk_example_Request_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.orbekk.example.CTR.Request.class, com.orbekk.example.CTR.Request.Builder.class);
      }

      // Construct using com.orbekk.example.CTR.Request.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        weekday_ = 0;

        hour_ = 0;

        bannerId_ = 0;

        geographic_ = 0;

        zoneId_ = 0;

        guid_ = 0L;

        domain_ = "";

        osCode_ = 0;

        browserCode_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.orbekk.example.CTR.internal_static_com_orbekk_example_Request_descriptor;
      }

      public com.orbekk.example.CTR.Request getDefaultInstanceForType() {
        return com.orbekk.example.CTR.Request.getDefaultInstance();
      }

      public com.orbekk.example.CTR.Request build() {
        com.orbekk.example.CTR.Request result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.orbekk.example.CTR.Request buildPartial() {
        com.orbekk.example.CTR.Request result = new com.orbekk.example.CTR.Request(this);
        result.weekday_ = weekday_;
        result.hour_ = hour_;
        result.bannerId_ = bannerId_;
        result.geographic_ = geographic_;
        result.zoneId_ = zoneId_;
        result.guid_ = guid_;
        result.domain_ = domain_;
        result.osCode_ = osCode_;
        result.browserCode_ = browserCode_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.orbekk.example.CTR.Request) {
          return mergeFrom((com.orbekk.example.CTR.Request)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.orbekk.example.CTR.Request other) {
        if (other == com.orbekk.example.CTR.Request.getDefaultInstance()) return this;
        if (other.getWeekday() != 0) {
          setWeekday(other.getWeekday());
        }
        if (other.getHour() != 0) {
          setHour(other.getHour());
        }
        if (other.getBannerId() != 0) {
          setBannerId(other.getBannerId());
        }
        if (other.getGeographic() != 0) {
          setGeographic(other.getGeographic());
        }
        if (other.getZoneId() != 0) {
          setZoneId(other.getZoneId());
        }
        if (other.getGuid() != 0L) {
          setGuid(other.getGuid());
        }
        if (!other.getDomain().isEmpty()) {
          domain_ = other.domain_;
          onChanged();
        }
        if (other.getOsCode() != 0) {
          setOsCode(other.getOsCode());
        }
        if (other.getBrowserCode() != 0) {
          setBrowserCode(other.getBrowserCode());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.orbekk.example.CTR.Request parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.orbekk.example.CTR.Request) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int weekday_ ;
      /**
       * <code>optional int32 weekday = 1;</code>
       */
      public int getWeekday() {
        return weekday_;
      }
      /**
       * <code>optional int32 weekday = 1;</code>
       */
      public Builder setWeekday(int value) {
        
        weekday_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 weekday = 1;</code>
       */
      public Builder clearWeekday() {
        
        weekday_ = 0;
        onChanged();
        return this;
      }

      private int hour_ ;
      /**
       * <code>optional int32 hour = 2;</code>
       */
      public int getHour() {
        return hour_;
      }
      /**
       * <code>optional int32 hour = 2;</code>
       */
      public Builder setHour(int value) {
        
        hour_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 hour = 2;</code>
       */
      public Builder clearHour() {
        
        hour_ = 0;
        onChanged();
        return this;
      }

      private int bannerId_ ;
      /**
       * <code>optional int32 bannerId = 3;</code>
       */
      public int getBannerId() {
        return bannerId_;
      }
      /**
       * <code>optional int32 bannerId = 3;</code>
       */
      public Builder setBannerId(int value) {
        
        bannerId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 bannerId = 3;</code>
       */
      public Builder clearBannerId() {
        
        bannerId_ = 0;
        onChanged();
        return this;
      }

      private int geographic_ ;
      /**
       * <code>optional int32 geographic = 4;</code>
       */
      public int getGeographic() {
        return geographic_;
      }
      /**
       * <code>optional int32 geographic = 4;</code>
       */
      public Builder setGeographic(int value) {
        
        geographic_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 geographic = 4;</code>
       */
      public Builder clearGeographic() {
        
        geographic_ = 0;
        onChanged();
        return this;
      }

      private int zoneId_ ;
      /**
       * <code>optional int32 zoneId = 5;</code>
       */
      public int getZoneId() {
        return zoneId_;
      }
      /**
       * <code>optional int32 zoneId = 5;</code>
       */
      public Builder setZoneId(int value) {
        
        zoneId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 zoneId = 5;</code>
       */
      public Builder clearZoneId() {
        
        zoneId_ = 0;
        onChanged();
        return this;
      }

      private long guid_ ;
      /**
       * <code>optional int64 guid = 6;</code>
       */
      public long getGuid() {
        return guid_;
      }
      /**
       * <code>optional int64 guid = 6;</code>
       */
      public Builder setGuid(long value) {
        
        guid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 guid = 6;</code>
       */
      public Builder clearGuid() {
        
        guid_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object domain_ = "";
      /**
       * <code>optional string domain = 7;</code>
       */
      public java.lang.String getDomain() {
        java.lang.Object ref = domain_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          domain_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string domain = 7;</code>
       */
      public com.google.protobuf.ByteString
          getDomainBytes() {
        java.lang.Object ref = domain_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          domain_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string domain = 7;</code>
       */
      public Builder setDomain(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        domain_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string domain = 7;</code>
       */
      public Builder clearDomain() {
        
        domain_ = getDefaultInstance().getDomain();
        onChanged();
        return this;
      }
      /**
       * <code>optional string domain = 7;</code>
       */
      public Builder setDomainBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        domain_ = value;
        onChanged();
        return this;
      }

      private int osCode_ ;
      /**
       * <code>optional int32 osCode = 8;</code>
       */
      public int getOsCode() {
        return osCode_;
      }
      /**
       * <code>optional int32 osCode = 8;</code>
       */
      public Builder setOsCode(int value) {
        
        osCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 osCode = 8;</code>
       */
      public Builder clearOsCode() {
        
        osCode_ = 0;
        onChanged();
        return this;
      }

      private int browserCode_ ;
      /**
       * <code>optional int32 browserCode = 9;</code>
       */
      public int getBrowserCode() {
        return browserCode_;
      }
      /**
       * <code>optional int32 browserCode = 9;</code>
       */
      public Builder setBrowserCode(int value) {
        
        browserCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 browserCode = 9;</code>
       */
      public Builder clearBrowserCode() {
        
        browserCode_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.orbekk.example.Request)
    }

    // @@protoc_insertion_point(class_scope:com.orbekk.example.Request)
    private static final com.orbekk.example.CTR.Request DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.orbekk.example.CTR.Request();
    }

    public static com.orbekk.example.CTR.Request getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Request>
        PARSER = new com.google.protobuf.AbstractParser<Request>() {
      public Request parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Request(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Request> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Request> getParserForType() {
      return PARSER;
    }

    public com.orbekk.example.CTR.Request getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.orbekk.example.Response)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 bannerId = 1;</code>
     */
    int getBannerId();

    /**
     * <code>optional float ctrPrediction = 2;</code>
     */
    float getCtrPrediction();
  }
  /**
   * Protobuf type {@code com.orbekk.example.Response}
   */
  public  static final class Response extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.orbekk.example.Response)
      ResponseOrBuilder {
    // Use Response.newBuilder() to construct.
    private Response(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Response() {
      bannerId_ = 0;
      ctrPrediction_ = 0F;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Response(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              bannerId_ = input.readInt32();
              break;
            }
            case 21: {

              ctrPrediction_ = input.readFloat();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.orbekk.example.CTR.internal_static_com_orbekk_example_Response_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.orbekk.example.CTR.internal_static_com_orbekk_example_Response_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.orbekk.example.CTR.Response.class, com.orbekk.example.CTR.Response.Builder.class);
    }

    public static final int BANNERID_FIELD_NUMBER = 1;
    private int bannerId_;
    /**
     * <code>optional int32 bannerId = 1;</code>
     */
    public int getBannerId() {
      return bannerId_;
    }

    public static final int CTRPREDICTION_FIELD_NUMBER = 2;
    private float ctrPrediction_;
    /**
     * <code>optional float ctrPrediction = 2;</code>
     */
    public float getCtrPrediction() {
      return ctrPrediction_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (bannerId_ != 0) {
        output.writeInt32(1, bannerId_);
      }
      if (ctrPrediction_ != 0F) {
        output.writeFloat(2, ctrPrediction_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (bannerId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, bannerId_);
      }
      if (ctrPrediction_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(2, ctrPrediction_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.orbekk.example.CTR.Response)) {
        return super.equals(obj);
      }
      com.orbekk.example.CTR.Response other = (com.orbekk.example.CTR.Response) obj;

      boolean result = true;
      result = result && (getBannerId()
          == other.getBannerId());
      result = result && (
          java.lang.Float.floatToIntBits(getCtrPrediction())
          == java.lang.Float.floatToIntBits(
              other.getCtrPrediction()));
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + BANNERID_FIELD_NUMBER;
      hash = (53 * hash) + getBannerId();
      hash = (37 * hash) + CTRPREDICTION_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getCtrPrediction());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.orbekk.example.CTR.Response parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.orbekk.example.CTR.Response parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.orbekk.example.CTR.Response parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.orbekk.example.CTR.Response parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.orbekk.example.CTR.Response parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.orbekk.example.CTR.Response parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.orbekk.example.CTR.Response parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.orbekk.example.CTR.Response parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.orbekk.example.CTR.Response parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.orbekk.example.CTR.Response parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.orbekk.example.CTR.Response prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.orbekk.example.Response}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.orbekk.example.Response)
        com.orbekk.example.CTR.ResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.orbekk.example.CTR.internal_static_com_orbekk_example_Response_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.orbekk.example.CTR.internal_static_com_orbekk_example_Response_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.orbekk.example.CTR.Response.class, com.orbekk.example.CTR.Response.Builder.class);
      }

      // Construct using com.orbekk.example.CTR.Response.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        bannerId_ = 0;

        ctrPrediction_ = 0F;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.orbekk.example.CTR.internal_static_com_orbekk_example_Response_descriptor;
      }

      public com.orbekk.example.CTR.Response getDefaultInstanceForType() {
        return com.orbekk.example.CTR.Response.getDefaultInstance();
      }

      public com.orbekk.example.CTR.Response build() {
        com.orbekk.example.CTR.Response result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.orbekk.example.CTR.Response buildPartial() {
        com.orbekk.example.CTR.Response result = new com.orbekk.example.CTR.Response(this);
        result.bannerId_ = bannerId_;
        result.ctrPrediction_ = ctrPrediction_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.orbekk.example.CTR.Response) {
          return mergeFrom((com.orbekk.example.CTR.Response)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.orbekk.example.CTR.Response other) {
        if (other == com.orbekk.example.CTR.Response.getDefaultInstance()) return this;
        if (other.getBannerId() != 0) {
          setBannerId(other.getBannerId());
        }
        if (other.getCtrPrediction() != 0F) {
          setCtrPrediction(other.getCtrPrediction());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.orbekk.example.CTR.Response parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.orbekk.example.CTR.Response) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int bannerId_ ;
      /**
       * <code>optional int32 bannerId = 1;</code>
       */
      public int getBannerId() {
        return bannerId_;
      }
      /**
       * <code>optional int32 bannerId = 1;</code>
       */
      public Builder setBannerId(int value) {
        
        bannerId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 bannerId = 1;</code>
       */
      public Builder clearBannerId() {
        
        bannerId_ = 0;
        onChanged();
        return this;
      }

      private float ctrPrediction_ ;
      /**
       * <code>optional float ctrPrediction = 2;</code>
       */
      public float getCtrPrediction() {
        return ctrPrediction_;
      }
      /**
       * <code>optional float ctrPrediction = 2;</code>
       */
      public Builder setCtrPrediction(float value) {
        
        ctrPrediction_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional float ctrPrediction = 2;</code>
       */
      public Builder clearCtrPrediction() {
        
        ctrPrediction_ = 0F;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.orbekk.example.Response)
    }

    // @@protoc_insertion_point(class_scope:com.orbekk.example.Response)
    private static final com.orbekk.example.CTR.Response DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.orbekk.example.CTR.Response();
    }

    public static com.orbekk.example.CTR.Response getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Response>
        PARSER = new com.google.protobuf.AbstractParser<Response>() {
      public Response parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Response(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Response> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Response> getParserForType() {
      return PARSER;
    }

    public com.orbekk.example.CTR.Response getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  /**
   * Protobuf service {@code com.orbekk.example.CTRPredictionService}
   */
  public static abstract class CTRPredictionService
      implements com.google.protobuf.Service {
    protected CTRPredictionService() {}

    public interface Interface {
      /**
       * <code>rpc GetPrediction(.com.orbekk.example.Request) returns (.com.orbekk.example.Response);</code>
       */
      public abstract void getPrediction(
          com.google.protobuf.RpcController controller,
          com.orbekk.example.CTR.Request request,
          com.google.protobuf.RpcCallback<com.orbekk.example.CTR.Response> done);

    }

    public static com.google.protobuf.Service newReflectiveService(
        final Interface impl) {
      return new CTRPredictionService() {
        @java.lang.Override
        public  void getPrediction(
            com.google.protobuf.RpcController controller,
            com.orbekk.example.CTR.Request request,
            com.google.protobuf.RpcCallback<com.orbekk.example.CTR.Response> done) {
          impl.getPrediction(controller, request, done);
        }

      };
    }

    public static com.google.protobuf.BlockingService
        newReflectiveBlockingService(final BlockingInterface impl) {
      return new com.google.protobuf.BlockingService() {
        public final com.google.protobuf.Descriptors.ServiceDescriptor
            getDescriptorForType() {
          return getDescriptor();
        }

        public final com.google.protobuf.Message callBlockingMethod(
            com.google.protobuf.Descriptors.MethodDescriptor method,
            com.google.protobuf.RpcController controller,
            com.google.protobuf.Message request)
            throws com.google.protobuf.ServiceException {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.callBlockingMethod() given method descriptor for " +
              "wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return impl.getPrediction(controller, (com.orbekk.example.CTR.Request)request);
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

        public final com.google.protobuf.Message
            getRequestPrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getRequestPrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return com.orbekk.example.CTR.Request.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

        public final com.google.protobuf.Message
            getResponsePrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getResponsePrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return com.orbekk.example.CTR.Response.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

      };
    }

    /**
     * <code>rpc GetPrediction(.com.orbekk.example.Request) returns (.com.orbekk.example.Response);</code>
     */
    public abstract void getPrediction(
        com.google.protobuf.RpcController controller,
        com.orbekk.example.CTR.Request request,
        com.google.protobuf.RpcCallback<com.orbekk.example.CTR.Response> done);

    public static final
        com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptor() {
      return com.orbekk.example.CTR.getDescriptor().getServices().get(0);
    }
    public final com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }

    public final void callMethod(
        com.google.protobuf.Descriptors.MethodDescriptor method,
        com.google.protobuf.RpcController controller,
        com.google.protobuf.Message request,
        com.google.protobuf.RpcCallback<
          com.google.protobuf.Message> done) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.callMethod() given method descriptor for wrong " +
          "service type.");
      }
      switch(method.getIndex()) {
        case 0:
          this.getPrediction(controller, (com.orbekk.example.CTR.Request)request,
            com.google.protobuf.RpcUtil.<com.orbekk.example.CTR.Response>specializeCallback(
              done));
          return;
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public final com.google.protobuf.Message
        getRequestPrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getRequestPrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return com.orbekk.example.CTR.Request.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public final com.google.protobuf.Message
        getResponsePrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getResponsePrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return com.orbekk.example.CTR.Response.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public static Stub newStub(
        com.google.protobuf.RpcChannel channel) {
      return new Stub(channel);
    }

    public static final class Stub extends com.orbekk.example.CTR.CTRPredictionService implements Interface {
      private Stub(com.google.protobuf.RpcChannel channel) {
        this.channel = channel;
      }

      private final com.google.protobuf.RpcChannel channel;

      public com.google.protobuf.RpcChannel getChannel() {
        return channel;
      }

      public  void getPrediction(
          com.google.protobuf.RpcController controller,
          com.orbekk.example.CTR.Request request,
          com.google.protobuf.RpcCallback<com.orbekk.example.CTR.Response> done) {
        channel.callMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          com.orbekk.example.CTR.Response.getDefaultInstance(),
          com.google.protobuf.RpcUtil.generalizeCallback(
            done,
            com.orbekk.example.CTR.Response.class,
            com.orbekk.example.CTR.Response.getDefaultInstance()));
      }
    }

    public static BlockingInterface newBlockingStub(
        com.google.protobuf.BlockingRpcChannel channel) {
      return new BlockingStub(channel);
    }

    public interface BlockingInterface {
      public com.orbekk.example.CTR.Response getPrediction(
          com.google.protobuf.RpcController controller,
          com.orbekk.example.CTR.Request request)
          throws com.google.protobuf.ServiceException;
    }

    private static final class BlockingStub implements BlockingInterface {
      private BlockingStub(com.google.protobuf.BlockingRpcChannel channel) {
        this.channel = channel;
      }

      private final com.google.protobuf.BlockingRpcChannel channel;

      public com.orbekk.example.CTR.Response getPrediction(
          com.google.protobuf.RpcController controller,
          com.orbekk.example.CTR.Request request)
          throws com.google.protobuf.ServiceException {
        return (com.orbekk.example.CTR.Response) channel.callBlockingMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          com.orbekk.example.CTR.Response.getDefaultInstance());
      }

    }

    // @@protoc_insertion_point(class_scope:com.orbekk.example.CTRPredictionService)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_orbekk_example_Request_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_orbekk_example_Request_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_orbekk_example_Response_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_orbekk_example_Response_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tCTR.proto\022\022com.orbekk.example\"\241\001\n\007Requ" +
      "est\022\017\n\007weekday\030\001 \001(\005\022\014\n\004hour\030\002 \001(\005\022\020\n\010ba" +
      "nnerId\030\003 \001(\005\022\022\n\ngeographic\030\004 \001(\005\022\016\n\006zone" +
      "Id\030\005 \001(\005\022\014\n\004guid\030\006 \001(\003\022\016\n\006domain\030\007 \001(\t\022\016" +
      "\n\006osCode\030\010 \001(\005\022\023\n\013browserCode\030\t \001(\005\"3\n\010R" +
      "esponse\022\020\n\010bannerId\030\001 \001(\005\022\025\n\rctrPredicti" +
      "on\030\002 \001(\0022b\n\024CTRPredictionService\022J\n\rGetP" +
      "rediction\022\033.com.orbekk.example.Request\032\034" +
      ".com.orbekk.example.ResponseB\003\210\001\001b\006proto" +
      "3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_orbekk_example_Request_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_orbekk_example_Request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_orbekk_example_Request_descriptor,
        new java.lang.String[] { "Weekday", "Hour", "BannerId", "Geographic", "ZoneId", "Guid", "Domain", "OsCode", "BrowserCode", });
    internal_static_com_orbekk_example_Response_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_orbekk_example_Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_orbekk_example_Response_descriptor,
        new java.lang.String[] { "BannerId", "CtrPrediction", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
