// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/java/com/orbekk/example/CTR.proto

package com.orbekk.example;

public final class CTR {
  private CTR() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface RequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.orbekk.example.Request)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 weekday = 1;</code>
     */
    boolean hasWeekday();
    /**
     * <code>required int32 weekday = 1;</code>
     */
    int getWeekday();

    /**
     * <code>required int32 hour = 2;</code>
     */
    boolean hasHour();
    /**
     * <code>required int32 hour = 2;</code>
     */
    int getHour();

    /**
     * <code>required int32 bannerId = 3;</code>
     */
    boolean hasBannerId();
    /**
     * <code>required int32 bannerId = 3;</code>
     */
    int getBannerId();

    /**
     * <code>required int32 geographic = 4;</code>
     */
    boolean hasGeographic();
    /**
     * <code>required int32 geographic = 4;</code>
     */
    int getGeographic();

    /**
     * <code>required int32 zoneId = 5;</code>
     */
    boolean hasZoneId();
    /**
     * <code>required int32 zoneId = 5;</code>
     */
    int getZoneId();

    /**
     * <code>required int64 guid = 6;</code>
     */
    boolean hasGuid();
    /**
     * <code>required int64 guid = 6;</code>
     */
    long getGuid();

    /**
     * <code>required string domain = 7;</code>
     */
    boolean hasDomain();
    /**
     * <code>required string domain = 7;</code>
     */
    java.lang.String getDomain();
    /**
     * <code>required string domain = 7;</code>
     */
    com.google.protobuf.ByteString
        getDomainBytes();

    /**
     * <code>required int32 osCode = 8;</code>
     */
    boolean hasOsCode();
    /**
     * <code>required int32 osCode = 8;</code>
     */
    int getOsCode();

    /**
     * <code>required int32 browserCode = 9;</code>
     */
    boolean hasBrowserCode();
    /**
     * <code>required int32 browserCode = 9;</code>
     */
    int getBrowserCode();
  }
  /**
   * Protobuf type {@code com.orbekk.example.Request}
   */
  public static final class Request extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.orbekk.example.Request)
      RequestOrBuilder {
    // Use Request.newBuilder() to construct.
    private Request(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Request(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Request defaultInstance;
    public static Request getDefaultInstance() {
      return defaultInstance;
    }

    public Request getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Request(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              weekday_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              hour_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              bannerId_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              geographic_ = input.readInt32();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              zoneId_ = input.readInt32();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              guid_ = input.readInt64();
              break;
            }
            case 58: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000040;
              domain_ = bs;
              break;
            }
            case 64: {
              bitField0_ |= 0x00000080;
              osCode_ = input.readInt32();
              break;
            }
            case 72: {
              bitField0_ |= 0x00000100;
              browserCode_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.orbekk.example.CTR.internal_static_com_orbekk_example_Request_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.orbekk.example.CTR.internal_static_com_orbekk_example_Request_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.orbekk.example.CTR.Request.class, com.orbekk.example.CTR.Request.Builder.class);
    }

    public static com.google.protobuf.Parser<Request> PARSER =
        new com.google.protobuf.AbstractParser<Request>() {
      public Request parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Request(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Request> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int WEEKDAY_FIELD_NUMBER = 1;
    private int weekday_;
    /**
     * <code>required int32 weekday = 1;</code>
     */
    public boolean hasWeekday() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 weekday = 1;</code>
     */
    public int getWeekday() {
      return weekday_;
    }

    public static final int HOUR_FIELD_NUMBER = 2;
    private int hour_;
    /**
     * <code>required int32 hour = 2;</code>
     */
    public boolean hasHour() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 hour = 2;</code>
     */
    public int getHour() {
      return hour_;
    }

    public static final int BANNERID_FIELD_NUMBER = 3;
    private int bannerId_;
    /**
     * <code>required int32 bannerId = 3;</code>
     */
    public boolean hasBannerId() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int32 bannerId = 3;</code>
     */
    public int getBannerId() {
      return bannerId_;
    }

    public static final int GEOGRAPHIC_FIELD_NUMBER = 4;
    private int geographic_;
    /**
     * <code>required int32 geographic = 4;</code>
     */
    public boolean hasGeographic() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required int32 geographic = 4;</code>
     */
    public int getGeographic() {
      return geographic_;
    }

    public static final int ZONEID_FIELD_NUMBER = 5;
    private int zoneId_;
    /**
     * <code>required int32 zoneId = 5;</code>
     */
    public boolean hasZoneId() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required int32 zoneId = 5;</code>
     */
    public int getZoneId() {
      return zoneId_;
    }

    public static final int GUID_FIELD_NUMBER = 6;
    private long guid_;
    /**
     * <code>required int64 guid = 6;</code>
     */
    public boolean hasGuid() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>required int64 guid = 6;</code>
     */
    public long getGuid() {
      return guid_;
    }

    public static final int DOMAIN_FIELD_NUMBER = 7;
    private java.lang.Object domain_;
    /**
     * <code>required string domain = 7;</code>
     */
    public boolean hasDomain() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>required string domain = 7;</code>
     */
    public java.lang.String getDomain() {
      java.lang.Object ref = domain_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          domain_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string domain = 7;</code>
     */
    public com.google.protobuf.ByteString
        getDomainBytes() {
      java.lang.Object ref = domain_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        domain_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int OSCODE_FIELD_NUMBER = 8;
    private int osCode_;
    /**
     * <code>required int32 osCode = 8;</code>
     */
    public boolean hasOsCode() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>required int32 osCode = 8;</code>
     */
    public int getOsCode() {
      return osCode_;
    }

    public static final int BROWSERCODE_FIELD_NUMBER = 9;
    private int browserCode_;
    /**
     * <code>required int32 browserCode = 9;</code>
     */
    public boolean hasBrowserCode() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <code>required int32 browserCode = 9;</code>
     */
    public int getBrowserCode() {
      return browserCode_;
    }

    private void initFields() {
      weekday_ = 0;
      hour_ = 0;
      bannerId_ = 0;
      geographic_ = 0;
      zoneId_ = 0;
      guid_ = 0L;
      domain_ = "";
      osCode_ = 0;
      browserCode_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasWeekday()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasHour()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasBannerId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasGeographic()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasZoneId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasGuid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasDomain()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasOsCode()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasBrowserCode()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, weekday_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, hour_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, bannerId_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, geographic_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(5, zoneId_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeInt64(6, guid_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeBytes(7, getDomainBytes());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeInt32(8, osCode_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeInt32(9, browserCode_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, weekday_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, hour_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, bannerId_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, geographic_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, zoneId_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(6, guid_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(7, getDomainBytes());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(8, osCode_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(9, browserCode_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.orbekk.example.CTR.Request parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.orbekk.example.CTR.Request parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.orbekk.example.CTR.Request parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.orbekk.example.CTR.Request parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.orbekk.example.CTR.Request parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.orbekk.example.CTR.Request parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.orbekk.example.CTR.Request parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.orbekk.example.CTR.Request parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.orbekk.example.CTR.Request parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.orbekk.example.CTR.Request parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.orbekk.example.CTR.Request prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.orbekk.example.Request}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.orbekk.example.Request)
        com.orbekk.example.CTR.RequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.orbekk.example.CTR.internal_static_com_orbekk_example_Request_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.orbekk.example.CTR.internal_static_com_orbekk_example_Request_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.orbekk.example.CTR.Request.class, com.orbekk.example.CTR.Request.Builder.class);
      }

      // Construct using com.orbekk.example.CTR.Request.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        weekday_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        hour_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        bannerId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        geographic_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        zoneId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        guid_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000020);
        domain_ = "";
        bitField0_ = (bitField0_ & ~0x00000040);
        osCode_ = 0;
        bitField0_ = (bitField0_ & ~0x00000080);
        browserCode_ = 0;
        bitField0_ = (bitField0_ & ~0x00000100);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.orbekk.example.CTR.internal_static_com_orbekk_example_Request_descriptor;
      }

      public com.orbekk.example.CTR.Request getDefaultInstanceForType() {
        return com.orbekk.example.CTR.Request.getDefaultInstance();
      }

      public com.orbekk.example.CTR.Request build() {
        com.orbekk.example.CTR.Request result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.orbekk.example.CTR.Request buildPartial() {
        com.orbekk.example.CTR.Request result = new com.orbekk.example.CTR.Request(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.weekday_ = weekday_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.hour_ = hour_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.bannerId_ = bannerId_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.geographic_ = geographic_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.zoneId_ = zoneId_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.guid_ = guid_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.domain_ = domain_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.osCode_ = osCode_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.browserCode_ = browserCode_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.orbekk.example.CTR.Request) {
          return mergeFrom((com.orbekk.example.CTR.Request)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.orbekk.example.CTR.Request other) {
        if (other == com.orbekk.example.CTR.Request.getDefaultInstance()) return this;
        if (other.hasWeekday()) {
          setWeekday(other.getWeekday());
        }
        if (other.hasHour()) {
          setHour(other.getHour());
        }
        if (other.hasBannerId()) {
          setBannerId(other.getBannerId());
        }
        if (other.hasGeographic()) {
          setGeographic(other.getGeographic());
        }
        if (other.hasZoneId()) {
          setZoneId(other.getZoneId());
        }
        if (other.hasGuid()) {
          setGuid(other.getGuid());
        }
        if (other.hasDomain()) {
          bitField0_ |= 0x00000040;
          domain_ = other.domain_;
          onChanged();
        }
        if (other.hasOsCode()) {
          setOsCode(other.getOsCode());
        }
        if (other.hasBrowserCode()) {
          setBrowserCode(other.getBrowserCode());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasWeekday()) {
          
          return false;
        }
        if (!hasHour()) {
          
          return false;
        }
        if (!hasBannerId()) {
          
          return false;
        }
        if (!hasGeographic()) {
          
          return false;
        }
        if (!hasZoneId()) {
          
          return false;
        }
        if (!hasGuid()) {
          
          return false;
        }
        if (!hasDomain()) {
          
          return false;
        }
        if (!hasOsCode()) {
          
          return false;
        }
        if (!hasBrowserCode()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.orbekk.example.CTR.Request parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.orbekk.example.CTR.Request) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int weekday_ ;
      /**
       * <code>required int32 weekday = 1;</code>
       */
      public boolean hasWeekday() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 weekday = 1;</code>
       */
      public int getWeekday() {
        return weekday_;
      }
      /**
       * <code>required int32 weekday = 1;</code>
       */
      public Builder setWeekday(int value) {
        bitField0_ |= 0x00000001;
        weekday_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 weekday = 1;</code>
       */
      public Builder clearWeekday() {
        bitField0_ = (bitField0_ & ~0x00000001);
        weekday_ = 0;
        onChanged();
        return this;
      }

      private int hour_ ;
      /**
       * <code>required int32 hour = 2;</code>
       */
      public boolean hasHour() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 hour = 2;</code>
       */
      public int getHour() {
        return hour_;
      }
      /**
       * <code>required int32 hour = 2;</code>
       */
      public Builder setHour(int value) {
        bitField0_ |= 0x00000002;
        hour_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 hour = 2;</code>
       */
      public Builder clearHour() {
        bitField0_ = (bitField0_ & ~0x00000002);
        hour_ = 0;
        onChanged();
        return this;
      }

      private int bannerId_ ;
      /**
       * <code>required int32 bannerId = 3;</code>
       */
      public boolean hasBannerId() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int32 bannerId = 3;</code>
       */
      public int getBannerId() {
        return bannerId_;
      }
      /**
       * <code>required int32 bannerId = 3;</code>
       */
      public Builder setBannerId(int value) {
        bitField0_ |= 0x00000004;
        bannerId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 bannerId = 3;</code>
       */
      public Builder clearBannerId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        bannerId_ = 0;
        onChanged();
        return this;
      }

      private int geographic_ ;
      /**
       * <code>required int32 geographic = 4;</code>
       */
      public boolean hasGeographic() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required int32 geographic = 4;</code>
       */
      public int getGeographic() {
        return geographic_;
      }
      /**
       * <code>required int32 geographic = 4;</code>
       */
      public Builder setGeographic(int value) {
        bitField0_ |= 0x00000008;
        geographic_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 geographic = 4;</code>
       */
      public Builder clearGeographic() {
        bitField0_ = (bitField0_ & ~0x00000008);
        geographic_ = 0;
        onChanged();
        return this;
      }

      private int zoneId_ ;
      /**
       * <code>required int32 zoneId = 5;</code>
       */
      public boolean hasZoneId() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required int32 zoneId = 5;</code>
       */
      public int getZoneId() {
        return zoneId_;
      }
      /**
       * <code>required int32 zoneId = 5;</code>
       */
      public Builder setZoneId(int value) {
        bitField0_ |= 0x00000010;
        zoneId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 zoneId = 5;</code>
       */
      public Builder clearZoneId() {
        bitField0_ = (bitField0_ & ~0x00000010);
        zoneId_ = 0;
        onChanged();
        return this;
      }

      private long guid_ ;
      /**
       * <code>required int64 guid = 6;</code>
       */
      public boolean hasGuid() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>required int64 guid = 6;</code>
       */
      public long getGuid() {
        return guid_;
      }
      /**
       * <code>required int64 guid = 6;</code>
       */
      public Builder setGuid(long value) {
        bitField0_ |= 0x00000020;
        guid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 guid = 6;</code>
       */
      public Builder clearGuid() {
        bitField0_ = (bitField0_ & ~0x00000020);
        guid_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object domain_ = "";
      /**
       * <code>required string domain = 7;</code>
       */
      public boolean hasDomain() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>required string domain = 7;</code>
       */
      public java.lang.String getDomain() {
        java.lang.Object ref = domain_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            domain_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string domain = 7;</code>
       */
      public com.google.protobuf.ByteString
          getDomainBytes() {
        java.lang.Object ref = domain_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          domain_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string domain = 7;</code>
       */
      public Builder setDomain(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        domain_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string domain = 7;</code>
       */
      public Builder clearDomain() {
        bitField0_ = (bitField0_ & ~0x00000040);
        domain_ = getDefaultInstance().getDomain();
        onChanged();
        return this;
      }
      /**
       * <code>required string domain = 7;</code>
       */
      public Builder setDomainBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        domain_ = value;
        onChanged();
        return this;
      }

      private int osCode_ ;
      /**
       * <code>required int32 osCode = 8;</code>
       */
      public boolean hasOsCode() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>required int32 osCode = 8;</code>
       */
      public int getOsCode() {
        return osCode_;
      }
      /**
       * <code>required int32 osCode = 8;</code>
       */
      public Builder setOsCode(int value) {
        bitField0_ |= 0x00000080;
        osCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 osCode = 8;</code>
       */
      public Builder clearOsCode() {
        bitField0_ = (bitField0_ & ~0x00000080);
        osCode_ = 0;
        onChanged();
        return this;
      }

      private int browserCode_ ;
      /**
       * <code>required int32 browserCode = 9;</code>
       */
      public boolean hasBrowserCode() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      /**
       * <code>required int32 browserCode = 9;</code>
       */
      public int getBrowserCode() {
        return browserCode_;
      }
      /**
       * <code>required int32 browserCode = 9;</code>
       */
      public Builder setBrowserCode(int value) {
        bitField0_ |= 0x00000100;
        browserCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 browserCode = 9;</code>
       */
      public Builder clearBrowserCode() {
        bitField0_ = (bitField0_ & ~0x00000100);
        browserCode_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.orbekk.example.Request)
    }

    static {
      defaultInstance = new Request(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.orbekk.example.Request)
  }

  public interface ResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.orbekk.example.Response)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 bannerId = 1;</code>
     */
    boolean hasBannerId();
    /**
     * <code>required int32 bannerId = 1;</code>
     */
    int getBannerId();

    /**
     * <code>required float ctrPrediction = 2;</code>
     */
    boolean hasCtrPrediction();
    /**
     * <code>required float ctrPrediction = 2;</code>
     */
    float getCtrPrediction();
  }
  /**
   * Protobuf type {@code com.orbekk.example.Response}
   */
  public static final class Response extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.orbekk.example.Response)
      ResponseOrBuilder {
    // Use Response.newBuilder() to construct.
    private Response(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Response(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Response defaultInstance;
    public static Response getDefaultInstance() {
      return defaultInstance;
    }

    public Response getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Response(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              bannerId_ = input.readInt32();
              break;
            }
            case 21: {
              bitField0_ |= 0x00000002;
              ctrPrediction_ = input.readFloat();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.orbekk.example.CTR.internal_static_com_orbekk_example_Response_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.orbekk.example.CTR.internal_static_com_orbekk_example_Response_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.orbekk.example.CTR.Response.class, com.orbekk.example.CTR.Response.Builder.class);
    }

    public static com.google.protobuf.Parser<Response> PARSER =
        new com.google.protobuf.AbstractParser<Response>() {
      public Response parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Response(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Response> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int BANNERID_FIELD_NUMBER = 1;
    private int bannerId_;
    /**
     * <code>required int32 bannerId = 1;</code>
     */
    public boolean hasBannerId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 bannerId = 1;</code>
     */
    public int getBannerId() {
      return bannerId_;
    }

    public static final int CTRPREDICTION_FIELD_NUMBER = 2;
    private float ctrPrediction_;
    /**
     * <code>required float ctrPrediction = 2;</code>
     */
    public boolean hasCtrPrediction() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required float ctrPrediction = 2;</code>
     */
    public float getCtrPrediction() {
      return ctrPrediction_;
    }

    private void initFields() {
      bannerId_ = 0;
      ctrPrediction_ = 0F;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasBannerId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCtrPrediction()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, bannerId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeFloat(2, ctrPrediction_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, bannerId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(2, ctrPrediction_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.orbekk.example.CTR.Response parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.orbekk.example.CTR.Response parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.orbekk.example.CTR.Response parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.orbekk.example.CTR.Response parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.orbekk.example.CTR.Response parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.orbekk.example.CTR.Response parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.orbekk.example.CTR.Response parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.orbekk.example.CTR.Response parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.orbekk.example.CTR.Response parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.orbekk.example.CTR.Response parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.orbekk.example.CTR.Response prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.orbekk.example.Response}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.orbekk.example.Response)
        com.orbekk.example.CTR.ResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.orbekk.example.CTR.internal_static_com_orbekk_example_Response_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.orbekk.example.CTR.internal_static_com_orbekk_example_Response_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.orbekk.example.CTR.Response.class, com.orbekk.example.CTR.Response.Builder.class);
      }

      // Construct using com.orbekk.example.CTR.Response.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        bannerId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        ctrPrediction_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.orbekk.example.CTR.internal_static_com_orbekk_example_Response_descriptor;
      }

      public com.orbekk.example.CTR.Response getDefaultInstanceForType() {
        return com.orbekk.example.CTR.Response.getDefaultInstance();
      }

      public com.orbekk.example.CTR.Response build() {
        com.orbekk.example.CTR.Response result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.orbekk.example.CTR.Response buildPartial() {
        com.orbekk.example.CTR.Response result = new com.orbekk.example.CTR.Response(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.bannerId_ = bannerId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.ctrPrediction_ = ctrPrediction_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.orbekk.example.CTR.Response) {
          return mergeFrom((com.orbekk.example.CTR.Response)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.orbekk.example.CTR.Response other) {
        if (other == com.orbekk.example.CTR.Response.getDefaultInstance()) return this;
        if (other.hasBannerId()) {
          setBannerId(other.getBannerId());
        }
        if (other.hasCtrPrediction()) {
          setCtrPrediction(other.getCtrPrediction());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasBannerId()) {
          
          return false;
        }
        if (!hasCtrPrediction()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.orbekk.example.CTR.Response parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.orbekk.example.CTR.Response) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int bannerId_ ;
      /**
       * <code>required int32 bannerId = 1;</code>
       */
      public boolean hasBannerId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 bannerId = 1;</code>
       */
      public int getBannerId() {
        return bannerId_;
      }
      /**
       * <code>required int32 bannerId = 1;</code>
       */
      public Builder setBannerId(int value) {
        bitField0_ |= 0x00000001;
        bannerId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 bannerId = 1;</code>
       */
      public Builder clearBannerId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        bannerId_ = 0;
        onChanged();
        return this;
      }

      private float ctrPrediction_ ;
      /**
       * <code>required float ctrPrediction = 2;</code>
       */
      public boolean hasCtrPrediction() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required float ctrPrediction = 2;</code>
       */
      public float getCtrPrediction() {
        return ctrPrediction_;
      }
      /**
       * <code>required float ctrPrediction = 2;</code>
       */
      public Builder setCtrPrediction(float value) {
        bitField0_ |= 0x00000002;
        ctrPrediction_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required float ctrPrediction = 2;</code>
       */
      public Builder clearCtrPrediction() {
        bitField0_ = (bitField0_ & ~0x00000002);
        ctrPrediction_ = 0F;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.orbekk.example.Response)
    }

    static {
      defaultInstance = new Response(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.orbekk.example.Response)
  }

  /**
   * Protobuf service {@code com.orbekk.example.CTRPredictionService}
   */
  public static abstract class CTRPredictionService
      implements com.google.protobuf.Service {
    protected CTRPredictionService() {}

    public interface Interface {
      /**
       * <code>rpc GetPrediction(.com.orbekk.example.Request) returns (.com.orbekk.example.Response);</code>
       */
      public abstract void getPrediction(
          com.google.protobuf.RpcController controller,
          com.orbekk.example.CTR.Request request,
          com.google.protobuf.RpcCallback<com.orbekk.example.CTR.Response> done);

    }

    public static com.google.protobuf.Service newReflectiveService(
        final Interface impl) {
      return new CTRPredictionService() {
        @java.lang.Override
        public  void getPrediction(
            com.google.protobuf.RpcController controller,
            com.orbekk.example.CTR.Request request,
            com.google.protobuf.RpcCallback<com.orbekk.example.CTR.Response> done) {
          impl.getPrediction(controller, request, done);
        }

      };
    }

    public static com.google.protobuf.BlockingService
        newReflectiveBlockingService(final BlockingInterface impl) {
      return new com.google.protobuf.BlockingService() {
        public final com.google.protobuf.Descriptors.ServiceDescriptor
            getDescriptorForType() {
          return getDescriptor();
        }

        public final com.google.protobuf.Message callBlockingMethod(
            com.google.protobuf.Descriptors.MethodDescriptor method,
            com.google.protobuf.RpcController controller,
            com.google.protobuf.Message request)
            throws com.google.protobuf.ServiceException {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.callBlockingMethod() given method descriptor for " +
              "wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return impl.getPrediction(controller, (com.orbekk.example.CTR.Request)request);
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

        public final com.google.protobuf.Message
            getRequestPrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getRequestPrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return com.orbekk.example.CTR.Request.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

        public final com.google.protobuf.Message
            getResponsePrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getResponsePrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return com.orbekk.example.CTR.Response.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

      };
    }

    /**
     * <code>rpc GetPrediction(.com.orbekk.example.Request) returns (.com.orbekk.example.Response);</code>
     */
    public abstract void getPrediction(
        com.google.protobuf.RpcController controller,
        com.orbekk.example.CTR.Request request,
        com.google.protobuf.RpcCallback<com.orbekk.example.CTR.Response> done);

    public static final
        com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptor() {
      return com.orbekk.example.CTR.getDescriptor().getServices().get(0);
    }
    public final com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }

    public final void callMethod(
        com.google.protobuf.Descriptors.MethodDescriptor method,
        com.google.protobuf.RpcController controller,
        com.google.protobuf.Message request,
        com.google.protobuf.RpcCallback<
          com.google.protobuf.Message> done) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.callMethod() given method descriptor for wrong " +
          "service type.");
      }
      switch(method.getIndex()) {
        case 0:
          this.getPrediction(controller, (com.orbekk.example.CTR.Request)request,
            com.google.protobuf.RpcUtil.<com.orbekk.example.CTR.Response>specializeCallback(
              done));
          return;
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public final com.google.protobuf.Message
        getRequestPrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getRequestPrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return com.orbekk.example.CTR.Request.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public final com.google.protobuf.Message
        getResponsePrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getResponsePrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return com.orbekk.example.CTR.Response.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public static Stub newStub(
        com.google.protobuf.RpcChannel channel) {
      return new Stub(channel);
    }

    public static final class Stub extends com.orbekk.example.CTR.CTRPredictionService implements Interface {
      private Stub(com.google.protobuf.RpcChannel channel) {
        this.channel = channel;
      }

      private final com.google.protobuf.RpcChannel channel;

      public com.google.protobuf.RpcChannel getChannel() {
        return channel;
      }

      public  void getPrediction(
          com.google.protobuf.RpcController controller,
          com.orbekk.example.CTR.Request request,
          com.google.protobuf.RpcCallback<com.orbekk.example.CTR.Response> done) {
        channel.callMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          com.orbekk.example.CTR.Response.getDefaultInstance(),
          com.google.protobuf.RpcUtil.generalizeCallback(
            done,
            com.orbekk.example.CTR.Response.class,
            com.orbekk.example.CTR.Response.getDefaultInstance()));
      }
    }

    public static BlockingInterface newBlockingStub(
        com.google.protobuf.BlockingRpcChannel channel) {
      return new BlockingStub(channel);
    }

    public interface BlockingInterface {
      public com.orbekk.example.CTR.Response getPrediction(
          com.google.protobuf.RpcController controller,
          com.orbekk.example.CTR.Request request)
          throws com.google.protobuf.ServiceException;
    }

    private static final class BlockingStub implements BlockingInterface {
      private BlockingStub(com.google.protobuf.BlockingRpcChannel channel) {
        this.channel = channel;
      }

      private final com.google.protobuf.BlockingRpcChannel channel;

      public com.orbekk.example.CTR.Response getPrediction(
          com.google.protobuf.RpcController controller,
          com.orbekk.example.CTR.Request request)
          throws com.google.protobuf.ServiceException {
        return (com.orbekk.example.CTR.Response) channel.callBlockingMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          com.orbekk.example.CTR.Response.getDefaultInstance());
      }

    }

    // @@protoc_insertion_point(class_scope:com.orbekk.example.CTRPredictionService)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_orbekk_example_Request_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_orbekk_example_Request_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_orbekk_example_Response_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_orbekk_example_Response_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n*src/main/java/com/orbekk/example/CTR.p" +
      "roto\022\022com.orbekk.example\"\241\001\n\007Request\022\017\n\007" +
      "weekday\030\001 \002(\005\022\014\n\004hour\030\002 \002(\005\022\020\n\010bannerId\030" +
      "\003 \002(\005\022\022\n\ngeographic\030\004 \002(\005\022\016\n\006zoneId\030\005 \002(" +
      "\005\022\014\n\004guid\030\006 \002(\003\022\016\n\006domain\030\007 \002(\t\022\016\n\006osCod" +
      "e\030\010 \002(\005\022\023\n\013browserCode\030\t \002(\005\"3\n\010Response" +
      "\022\020\n\010bannerId\030\001 \002(\005\022\025\n\rctrPrediction\030\002 \002(" +
      "\0022b\n\024CTRPredictionService\022J\n\rGetPredicti" +
      "on\022\033.com.orbekk.example.Request\032\034.com.or" +
      "bekk.example.ResponseB\003\210\001\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_orbekk_example_Request_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_orbekk_example_Request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_orbekk_example_Request_descriptor,
        new java.lang.String[] { "Weekday", "Hour", "BannerId", "Geographic", "ZoneId", "Guid", "Domain", "OsCode", "BrowserCode", });
    internal_static_com_orbekk_example_Response_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_orbekk_example_Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_orbekk_example_Response_descriptor,
        new java.lang.String[] { "BannerId", "CtrPrediction", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
